version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      deps:
        dependency-type: production
      deps-dev:
        dependency-type: development
    ignore:
      # https://github.com/vercel/next.js/issues/64409
      - dependency-name: eslint
        versions:
          - ">= 9"
