name: Build and deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'mock/**'
      - 'infra/**'
      - '.github/**'
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: yarn install && yarn build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to S3 with cache directives
        run: |
          aws s3 sync \
            --delete \
            --cache-control max-age=604800 \
            --exclude "*.html" \
            ./out s3://${{ secrets.S3_BUCKET }}
          aws s3 sync \
            --delete \
            --cache-control no-cache \
            --exclude "*" \
            --include "*.html" \
            ./out s3://${{ secrets.S3_BUCKET }}