name: Upload posts

on:
  push: 
    branches:
      - main
    paths:
      - 'content/posts/**.md'
  workflow_dispatch:
    branches:
      - main

jobs:
  upload_posts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions/upload-posts
          role-session-name: gh-actions
          aws-region: ap-southeast-2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install boto3 python-frontmatter

      - run: python scripts/upload_posts.py
        env:
          TABLE_NAME: ${{ secrets.DYNAMODB_TABLE }}
    